spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mtwas
    username: root
    password: Sindhur@2005

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true